[package]
name = "waylock"
version = "0.1.0"
edition = "2021"

[dependencies]
pam = { version = "0.8.0", default-features = false, features = ["client"]}
iced = { version = "0.12.1", default-features = false}
iced_sessionlock = { version = "0.6.0", default-features = false }
